<?php

/*
 * Copyright (C) 2026 pvols79
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

namespace OPNsense\SplunkHEC\Api;

use OPNsense\Base\ApiMutableModelControllerBase;
use OPNsense\Core\Backend;
use OPNsense\Core\Config;

class ServiceController extends ApiMutableModelControllerBase
{
    /** @var string model class name */
    protected static $internalModelName = 'SplunkHEC';

    /** @var string fully-qualified model class */
    protected static $internalModelClass = 'OPNsense\\SplunkHEC\\SplunkHEC';

    /**
     * GET /api/splunkhec/service/get
     *
     * Return all current settings (general + logs sections).
     * mapDataToFormUI() uses the keys to populate form fields by dot-notation ID.
     *
     * @return array
     */
    public function getAction()
    {
        $result = [];
        if ($this->request->isGet()) {
            $mdl   = $this->getModel();
            $nodes = $mdl->getNodes();
            $result['general'] = $nodes['general'];
            $result['logs']    = $nodes['logs'];
        }
        return $result;
    }

    /**
     * POST /api/splunkhec/service/set
     *
     * Persist settings submitted from the UI.
     * Note: setBase() in OPNsense 26.7 is UUID-based (grid rows only),
     * so we use direct model manipulation for flat settings pages.
     *
     * @return array
     */
    public function setAction()
    {
        $result = ['result' => 'failed'];

        if ($this->request->isPost()) {
            $mdl  = $this->getModel();
            $post = $this->request->getPost();

            // setNodes() traverses the posted array and sets matching model fields
            $mdl->setNodes($post);

            $valMsgs = $mdl->validate();
            if (count($valMsgs) > 0) {
                $result['validations'] = $valMsgs;
            } else {
                $mdl->serializeToConfig();
                Config::getInstance()->save();

                // Write the INI file the daemon reads at startup
                $this->writeIniConfig($mdl);

                // Reload the daemon so new settings take effect immediately
                try {
                    $backend = new Backend();
                    $backend->configdRun('splunk_hec restart');
                } catch (\Exception $e) {
                    // Log but don't fail the save — daemon may not be running yet
                    syslog(LOG_WARNING, 'SplunkHEC: could not restart daemon: ' . $e->getMessage());
                }

                $result['result'] = 'saved';
            }
        }

        return $result;
    }

    /**
     * GET /api/splunkhec/service/status
     *
     * @return array
     */
    public function statusAction()
    {
        $backend  = new Backend();
        $response = trim($backend->configdRun('splunk_hec status'));
        return ['status' => ($response === 'running') ? 'running' : 'stopped'];
    }

    /**
     * Serialize current model values into the INI file consumed by Exporter.php.
     * Written to /var/etc/splunk_hec.conf on every save.
     *
     * @param \OPNsense\SplunkHEC\SplunkHEC $mdl
     */
    private function writeIniConfig($mdl)
    {
        $g = $mdl->general;
        $l = $mdl->logs;

        $ini  = "; Auto-generated by OPNsense SplunkHEC plugin — do not edit.\n";
        $ini .= "[splunk_hec]\n";
        $ini .= 'enabled = '    . (string)$g->enabled    . "\n";
        $ini .= 'token = '      . (string)$g->token      . "\n";
        $ini .= 'endpoint = '   . (string)$g->endpoint   . "\n";
        $ini .= 'cache_size = ' . (string)$g->cache_size . "\n";
        $ini .= 'cache_time = ' . (string)$g->cache_time . "\n";
        $ini .= "\n[logs]\n";
        $ini .= 'system = ' . (string)$l->system . "\n";
        $ini .= 'filter = ' . (string)$l->filter . "\n";

        @mkdir('/var/etc', 0755, true);
        file_put_contents('/var/etc/splunk_hec.conf', $ini);
    }
}
