<?php

/**
 * OPNsense Splunk HEC Plugin – API Service Controller
 *
 * Handles configuration persistence and daemon management for the
 * Splunk HTTP Event Collector log exporter.
 *
 * @license BSD-2-Clause
 */

namespace OPNsense\SplunkHEC\Api;

use OPNsense\Base\ApiMutableModelControllerBase;
use OPNsense\Core\Backend;
use OPNsense\Core\Config;

class ServiceController extends ApiMutableModelControllerBase
{
    /**
     * Model class reference.
     * @var string
     */
    protected static $internalModelName = 'SplunkHEC';

    /**
     * Fully-qualified model class.
     * @var string
     */
    protected static $internalModelClass = 'OPNsense\\SplunkHEC\\SplunkHEC';

    /**
     * GET  /api/splunkhec/service/get
     *
     * Return the current model configuration.
     *
     * @return array
     */
    public function getAction()
    {
        return $this->getBase('general', 'general');
    }

    /**
     * POST /api/splunkhec/service/set
     *
     * Persist the configuration submitted from the UI, write the INI
     * file consumed by the daemon, and restart the service.
     *
     * @return array
     */
    public function setAction()
    {
        $result = $this->setBase('general', 'general');

        if ($result['result'] !== 'failed') {
            // Write the INI config file consumed by the daemon script.
            $this->writeIniConfig();

            // Restart the daemon via configd so the new settings take effect.
            $backend = new Backend();
            $backend->configdRun('splunk_hec restart');
        }

        return $result;
    }

    /**
     * GET  /api/splunkhec/service/status
     *
     * Return the running status of the exporter daemon.
     *
     * @return array
     */
    public function statusAction()
    {
        $backend = new Backend();
        $response = trim($backend->configdRun('splunk_hec status'));

        return [
            'status' => $response === 'running' ? 'running' : 'stopped',
        ];
    }

    /**
     * Serialize current model values into the INI file that the
     * Exporter.php daemon reads at startup.
     */
    private function writeIniConfig()
    {
        $mdl = $this->getModel();
        $node = $mdl->general;

        $ini  = "; Auto-generated by OPNsense SplunkHEC plugin — do not edit.\n";
        $ini .= "[splunk_hec]\n";
        $ini .= 'enabled = ' . (string)$node->enabled . "\n";
        $ini .= 'token = '   . (string)$node->token   . "\n";
        $ini .= 'endpoint = '. (string)$node->endpoint . "\n";
        $ini .= 'logs = '    . (string)$node->logs     . "\n";
        $ini .= 'cache_size = ' . (string)$node->cache_size . "\n";
        $ini .= 'cache_time = ' . (string)$node->cache_time . "\n";

        @mkdir(dirname('/var/etc/splunk_hec.conf'), 0755, true);
        file_put_contents('/var/etc/splunk_hec.conf', $ini);
    }
}
