<?php

/*
 * Copyright (C) 2026 pvols79
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

namespace OPNsense\SplunkHEC\Api;

use OPNsense\Base\ApiMutableModelControllerBase;
use OPNsense\Core\Backend;
use OPNsense\Core\Config;

class ServiceController extends ApiMutableModelControllerBase
{
    /** @var string model class name */
    protected static $internalModelName = 'SplunkHEC';

    /** @var string fully-qualified model class */
    protected static $internalModelClass = 'OPNsense\\SplunkHEC\\SplunkHEC';

    /**
     * GET /api/splunkhec/service/get
     *
     * Return all current settings (general + logs sections).
     * mapDataToFormUI() uses the top-level keys to populate form fields
     * by dot-notation ID (e.g. general.enabled, logs.system).
     */
    public function getAction()
    {
        $result = [];
        if ($this->request->isGet()) {
            $mdl   = $this->getModel();
            $nodes = $mdl->getNodes();
            $result['general'] = $nodes['general'];
            $result['logs']    = $nodes['logs'];
        }
        return $result;
    }

    /**
     * POST /api/splunkhec/service/set
     *
     * Persist settings submitted from the UI. Save only — does NOT restart
     * the daemon. The separate reconfigureAction() does that, called after
     * this by SimpleActionButton's data-endpoint lifecycle.
     *
     * Note: setBase() in OPNsense 26.7+ is UUID-based (grid rows only).
     * For flat settings pages we use setNodes() + validate() directly.
     */
    public function setAction()
    {
        $result = ['result' => 'failed'];

        if ($this->request->isPost()) {
            $mdl  = $this->getModel();
            $post = $this->request->getPost();

            $mdl->setNodes($post);

            $valMsgs = $mdl->validate();
            if (count($valMsgs) > 0) {
                $result['validations'] = $valMsgs;
            } else {
                $mdl->serializeToConfig();
                Config::getInstance()->save();
                $this->writeIniConfig($mdl);
                $result['result'] = 'saved';
            }
        }

        return $result;
    }

    /**
     * POST /api/splunkhec/service/reconfigure
     *
     * Apply the saved configuration by restarting the daemon.
     * Called by SimpleActionButton after setAction() succeeds.
     * This is the endpoint that controls the spinner lifecycle.
     */
    public function reconfigureAction()
    {
        $result = ['result' => 'failed'];

        if ($this->request->isPost()) {
            try {
                $backend = new Backend();
                $backend->configdRun('splunk_hec restart');
                $result['result'] = 'ok';
            } catch (\Exception $e) {
                syslog(LOG_WARNING, 'SplunkHEC: reconfigure failed: ' . $e->getMessage());
            }
        }

        return $result;
    }

    /**
     * GET /api/splunkhec/service/status
     */
    public function statusAction()
    {
        $backend  = new Backend();
        $response = trim($backend->configdRun('splunk_hec status'));
        return ['status' => ($response === 'running') ? 'running' : 'stopped'];
    }

    /**
     * Serialize current model values into the INI file consumed by Exporter.php.
     * Written to /var/etc/splunk_hec.conf on every successful save.
     */
    private function writeIniConfig($mdl)
    {
        $g = $mdl->general;
        $l = $mdl->logs;

        $ini  = "; Auto-generated by OPNsense SplunkHEC plugin — do not edit.\n";
        $ini .= "[splunk_hec]\n";
        $ini .= 'enabled = '    . (string)$g->enabled    . "\n";
        $ini .= 'token = '      . (string)$g->token      . "\n";
        $ini .= 'endpoint = '   . (string)$g->endpoint   . "\n";
        $ini .= 'cache_size = ' . (string)$g->cache_size . "\n";
        $ini .= 'cache_time = ' . (string)$g->cache_time . "\n";
        $ini .= "\n[logs]\n";
        $ini .= 'system = ' . (string)$l->system . "\n";
        $ini .= 'filter = ' . (string)$l->filter . "\n";

        @mkdir('/var/etc', 0755, true);
        file_put_contents('/var/etc/splunk_hec.conf', $ini);
    }
}
