[restart]
command:/usr/local/etc/rc.d/configd restart_splunk_hec
parameters:
type:script
message:Restarting Splunk HEC exporter

[start]
command:/usr/local/opnsense/scripts/OPNsense/SplunkHEC/Exporter.php
parameters:
type:script
message:Starting Splunk HEC exporter

[stop]
command:/bin/pkill -f Exporter.php
parameters:
type:script
message:Stopping Splunk HEC exporter

[status]
command:/bin/pgrep -f Exporter.php && echo 'running' || echo 'stopped'
parameters:
type:script_output
message:Requesting Splunk HEC exporter status
